urls.py
from django.conf.urls.defaults import *
from trs.views import *
#from trs.views.place import *


#from trs_web.trs.views.place import *
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
from trs.views.forms import PlaceForm
from trs.views.device import DeviceForm
import os
PROJECT_DIR = os.path.dirname(__file__)



urlpatterns =\
patterns('',
         # Example:
         # (r'^trs_web/', include('trs_web.foo.urls')),
         (r'^$', views.ticket_list),
         url(r'^ticket/(\d{1,6})/$', ticket.message_list, name="ticket"),
         (r'^edit_ticket/$', ticket.edit_ticket),
         #(r'^new_ticket/$', ticket.add_ticket),
         url(r'^create_ticket/for-user/(?P<user_id>\d{1,6})$', views.TicketCreate.as_view()),
         #url(r'^add_ticket/user/(\d{1,6})/(\w+)/$', ticket.add_ticket, name="new_ticket"),
         #url(r'^add_ticket/user/(?P<user_id>\d{1,6})/(?P<status>\w+)/$', ticket.TicketView.exec_save, name="new_ticket"),


         #url(r'^ticket/(?P<id>\d{1,6})/$', ticket.TicketView.exec_update, name="ticket"),

         #url(r'^user/(?P<id>\d{1,6})/$', user.UserView.exec_update, name="user"),
         url(r'^create_user$', views.UserCreate.as_view(), name="user_create"),
         url(r'^user/(?P<pk>\d+)/edit/$', views.UserUpdate.as_view(), name="user_update"),
         url(r'^create_(\w+)$', views.generic_create, name="create"),
         (r'^places/$', place.places),
         (r'^place/(\d{1,6})$', place.places),
         (r'^user_to_place/(\d{1,6})/(\d{1,6})$', views.user_to_place),
         #(r'^add_place/$', place.add_place),
         
         url(r'^add_ticket/user/(?P<user_id>\d{1,6})/(?P<status>\w+)/$', views.generic_create,name="add_ticket"),

         url(r'^edit_(\w+)/(\d{1,6})/$', views.generic_edit, name="edit"),
         (r'^delete_(\w+)/(\d{1,6})$', views.generic_delete),
         (r'^ajax/(\w+)/(\d{1,6})$', views.generic_jget),
         (r'^ajax/users$', views.ajax_users),

         (r'^validate/device/$', 'ajax_validation.views.validate', {'form_class': DeviceForm},
          'device_form_validate'),
         (r'^validate/place/$', 'ajax_validation.views.validate', {'form_class': PlaceForm},
          'device_form_validate'),

         (r'^del_place/(\d{1,6})$', place.del_place),

         (r'^doc_upload/$', place.doc_upload),
         (r'^search_users/$', views.search_users),
         (r'^ticket_reply/$', views.ticket_reply),
         (r'^login/$', views.login),
         (r'^logout/$', views.logout),
         url(r'^options/$', views.options, name="options"),
         url(r'^media/(?P<path>.*)$', "django.views.static.serve",
         {'document_root': os.path.join(PROJECT_DIR,"media") }
             ),

         # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
         # to INSTALLED_APPS to enable admin documentation:
         # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

         # Uncomment the next line to enable the admin:
         # (r'^admin/', include(admin.site.urls)),
         )

trs/models.py
# -*- coding: utf8 -*-
from django.db import models
import custom_fields
import datetime
#import mptt

# Create your models here.
class Message(models.Model):
    user = models.ForeignKey('User')
    time = models.DateTimeField(auto_now=True,auto_now_add=True)
    text = models.TextField()
    #true если это ответ поддержки
    reply = models.BooleanField(default=False)
    ticket = models.ForeignKey('Ticket')
    ip = models.IPAddressField(blank=True,null=True)
    

class User(models.Model):
    name = models.CharField("Имя",max_length=60)
    email = models.EmailField(blank=True,null=True)
    phone = models.CharField("Внутр. телефон",max_length=30,blank=True,null=True)
    mobile = models.CharField("Корп. мобильный",max_length=30,blank=True,null=True)
    city_phone = models.CharField("Городской телефон",max_length=30,blank=True,null=True)
    sat_phone = models.CharField("Спутниковый телефон",max_length=30,blank=True,null=True)
    personal_phone = models.CharField("Личный телефон",max_length=30,blank=True,null=True)
    admin = models.BooleanField(default=False)
    login = models.CharField(max_length=16,blank=True,null=True)
    password = models.CharField(max_length=32,blank=True,null=True)
    place = models.ForeignKey('Place',blank=True,null=True)

class Device(models.Model):
    TYPE_CHOICES=(
        ('00','Компьютер'),
        ('10','Монитор'),
        ('20','Принтер'),
        ('30','МФУ'),
        ('40','Плоттер'),
        ('50','Сканер'),
        ('60','Сервер'),
        ('70','Маршрутизатор'),
        ('80','Модем'),
    )
    type=models.CharField(max_length=3,choices=TYPE_CHOICES)
    inv_no=models.CharField(max_length=40)
    ip=models.IPAddressField(blank=True,null=True)
    model=models.CharField(max_length=60,blank=True,null=True)
    mac=custom_fields.MACAddressField(blank=True,null=True)
    info=models.TextField(blank=True,null=True)
    place = models.ForeignKey('Place')
    hostname=models.CharField(blank=True,null=True,max_length=40)
    def type_display(self):        
        for desc in self.TYPE_CHOICES:
            if desc[0]==self.type:
                return desc[1]
    def get_absolute_url(self):
        return "/place/"+str(self.place.id)

class Ticket(models.Model):
    #NEW,OPEN,CLOSED,DELETED
    STATUS_CHOICES=(
        ('00','Новое'),
        ('10','Принято'),
        ('20','Ожидаем ответ'),
        ('30','Закрыто'),
        ('40','Удалено'),        
    )
    PRIO_CHOICES=(
        ('00','Крайне срочно'),
        ('10','Срочно'),
        ('20','Обычно'),
        ('30','Длительное')
    )

    CATEGORY_CHOICES=(
        ('00','Компьютеры, локальный софт, железо'),
        ('10','Печать, принтеры, расходники'),
        ('20','Корпоративные системы (SAP,АСУД ..)'),
        ('30','Сетевые сервисы и оборуд., Серверы'),
        ('40','СКС (провода, розетки)'),
    
    )

    status = models.CharField("Статус",max_length=3, choices=STATUS_CHOICES)
    priority = models.CharField("Приоритет",max_length=3, choices=PRIO_CHOICES)
    category = models.CharField("Категория",max_length=3, choices=CATEGORY_CHOICES,blank=True,null=True)
    hours_limit=models.DecimalField("Лимит времени, ч.",max_digits=4, decimal_places=1,default=2)
    #Описание проблемы. при создании тикета - присваиваем текст 1го обращения
    #В процессе выполнения заявки можем менять
    description = models.TextField("Описание проблемы")
    #Описание решения по закрытии заявки
    resume = models.TextField("Отчёт о решении",blank=True,null=True)
    user = models.ForeignKey(User,related_name="tickets")
    admin = models.ForeignKey(User,related_name="tasks",blank=True,null=True)
    device = models.ForeignKey(Device,blank=True,null=True)    
    #Время создания. 
    ctime = models.DateTimeField(auto_now_add = True)
    #Время закрытия
    closing_time = models.DateTimeField(blank=True,null=True)

    def get_short_text(self):
        return self.description[:120]
    
    def hours_from_now(self):
        delta=datetime.datetime.now()-self.ctime
        return round(delta.days*24.0+delta.seconds/3600.0,1)

    def is_new(self,*args):
        value=self.status
        if args:
            value=args[0]
        if value=='00':
            return True
        else:
            return False

    def is_closed(self,*args):
        value=self.status
        if args:
            value=args[0]
        if value=='30':
            return True
        else:
            return False
        
    def accept_by(self,user):
        self.admin=user
        
    def no(self):
        return '{0:0>5}'.format(self.id)
        
class Place(models.Model):
    name = models.CharField(max_length=60)
    parent = models.ForeignKey('self',null=True, blank=True )
    address = models.CharField(max_length=70)
    LEVEL_DESC=(
    (1,"Населённый пункт"),
    (2,"Территория, группа зданий"),
    (3,"Здание"),
    (4,"Этаж"),
    (5,"Кабинет/помещение"),
    (6,"Место/комплекс"),
    )
    def childs(self):
        return Place.objects.filter(parent=self)
    
    def get_level(self):
        res=0
        try:
            if self.parent!=None:
                o=self
                while (o.parent !=None):
                    res+=1
                    o=o.parent
        except:
            None
        return res
    
    def level_display(self):
        level=self.get_level()
        for desc in self.LEVEL_DESC:
            if desc[0]==level:
                return desc[1]
    
    def path(self):        
        path=[]
        o=self
        while (o.parent != None):
            path.insert(0,o)
            o=o.parent
        path.insert(0,o)
        return path
    def get_absolute_url(self):
        return '/place/'+str(self.id)
    def __unicode__(self):
        return self.name
    
    def users(self):
        return User.objects.filter(place=self)

#mptt.register(Place)

class Document(models.Model):
    name=models.CharField(max_length=60)
    place=models.ForeignKey(Place,blank=True,null=True)
    def latest_file(self):
        return DocFile.objects.filter(document=self).order_by('-id')[0]
    
class DocFile(models.Model):
    document=models.ForeignKey(Document)
    version=models.IntegerField()
    file_name=models.CharField(max_length=60)
    comment=models.CharField(max_length=90,blank=True,null=True)
    ctime = models.DateTimeField()
    user = models.ForeignKey(User)
    

trs/views/place.py
# -*- coding: utf8 -*-
from datetime import datetime
import os
from django.http import Http404, HttpResponse
from django.shortcuts import render_to_response, redirect
from trs.models import Device, Document, Place, DocFile
from trs.views.device import DeviceForm
from trs.views.forms import PlaceForm, PlaceDocumentForm
from trs.views.helpers import session_user

__author__ = 'boris'

def places(request, id=22):
    try:
        id = int(id)
    except ValueError:
        raise Http404()
    item = Place.objects.get(id=id)
    root = Place.objects.get(id=22)
    form = PlaceDocumentForm()
    place_form = PlaceForm()
    device_form = DeviceForm()
    docs = Document.objects.filter(place=item)
    # places = Place.objects.all()
    devices = Device.objects.filter(place=item)

    def li(item, idpref):
        res = '<li id="' + idpref + str(item.id) + '">'
        res += '<a href="' + item.get_absolute_url() + '">' + item.name + '</a>'
        res += '<ul>'
        for c in item.childs():
            res += li(c, idpref)
            #print li(c,idpref)
        res += '</ul>'
        res += '</li>'
        return res

    return render_to_response('places.html',
                              {'tree': li(root, 'place_'),
                               'root': item, 'docs': docs, 'form': form,
                               'place_form': place_form, 'device_form': device_form,
                               'devices': devices})


#def add_place(request):
#    parent_id = 0
#    try:
#        par = Place.objects.get(id=request.POST.get('parent_id'))
#        parent_id = par.id
#        p = Place(parent=par)
#        form = PlaceForm(request.POST, instance=p)
#        form.save(commit=True)
#    except:
#        None
#    return redirect('/place/' + str(parent_id))
#
def del_place(request, place_id=None):
    parent_id = 0
    try:
        place_id = int(place_id)
        parent_id = Place.objects.get(id=place_id).parent.id
        Place.objects.get(id=place_id).delete()
    except ValueError:
        raise Http404()

    return redirect('/place/' + str(parent_id))

#-------------------------------------Document upload
INPUT_PATH = "d:/input"

def gen_filename(fname):
    if not os.path.exists(INPUT_PATH + '/' + fname):
        return fname
    else:
        spl = fname.rsplit('.', 1)
        name = spl[0]
        ext = spl[1]
        fname = name + '_.' + ext
        return gen_filename(fname)

def doc_upload(request):
    if request.method == 'POST':
        form = PlaceDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            cd = form.cleaned_data
            #return HttpResponse(str(cd))
            place = Place.objects.get(id=cd['place_id'])
            #doc = None
            #title = None
            #Существущий документ (обновляем название)
            if cd['doc_id'] is not None:
                doc = Document.objects.get(id=int(cd['doc_id']))
                if cd['name'] != '':
                    doc.name = cd['name']
                    doc.save()
            #Новый документ
            else:
                title = cd['name'] if cd['name'] != '' else request.FILES['file'].name
                doc = Document(name=title, place=place)
                doc.save()
                #Создаём DocFile
            doc_file = DocFile(document=doc, version=0, file_name='temp',
                               comment=cd['comment'],
                               ctime=datetime.datetime.now(),
                               user=session_user(request))
            doc_file.save()
            #id.ext

            fname = str(doc_file.id) + '.' + request.FILES['file'].name.rsplit('.', 1)[1]
            doc_file.file_name = fname
            doc_file.save()
            #Сохраняем файл
            destination = open(INPUT_PATH + '/' + fname, 'wb+')
            for chunk in request.FILES['file'].chunks():
                destination.write(chunk)
            destination.close()
            return redirect('/place/' + str(cd['place_id']))
        else:
            return HttpResponse(str(form.errors))


  

templates/add_ticket.html
{% extends "base.html" %}
{% block title %}- Новое обращение{% endblock %}
{% block content %}
<div style="position:relative">
<div id="ticket_form">
<h3>Новое обращение пользователя {{foruser.name}}</h3>
{% if mail_error %}
<div class="mail_error">Отправка email не удалась</br>Ошибка: {{mail_error}}</div>
{% endif %}
<form method="post" action="/new_ticket/">    
    {{form.errors}}
	{% for field in form.visible_fields %}				
		<div class="field_wrapper">
		{{field.label_tag}}
		{{field}}
		</div>
	{% endfor %}
    <input type="hidden" name="user_id" value="{{foruser.id}}"/>
    <input type="submit" value="Создать"/>
</form>
</div>
<div id="ticket_messages">
<h4>История обращений</h4>
{% for t in tickets %}
<ul>
<li>{{t.description}} <i>({{t.ctime|date:"d.m.Y"}} #{{t.id}})</i></li>

{% if t.admin %}
<ul><li>{{t.admin.login}}:
	{% if t.resume %}	
	<b>{{t.resume}}</b>
	{% endif %}
	</li>
</ul>
{% endif %}
</ul>
{% endfor %}
</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"  content="text/html;charset=utf-8" >  
  <title>IT Workspace {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="/media/style.css" type="text/css">
  {% block head %}{% endblock %}
</head>
<body>

    <div class="head">
            <div class="title">IT Workspace</div> 
            <div class="logout"><a href="/logout/">[logout]</a></div>
    </div>
    <div class="menu">
            <a href="/">[Обращения]</a>
            <a href="/search_users/">[Пользователи]</a>
            <a href="/options/">[Настройки]</a>
           <!-- <a href="/places/">[Места]</a> -->
    </div>
<div id="wrap">
    <div id="main">
        {% block content %}{% endblock %}
    </div>
    </div>
    <div id="footer">
    (c) ОСП ПО ЦВР МЭС Востока - Амурский участок ИТС
    </div>
</body>
</html>

templates/error.html
{% extends "base.html" %}
{% block title %}- Ошибка{% endblock %}
{% block content %}
<a href="javascript:history.back()">&lt;&lt;Назад</a>
<h3>{{short}}</h3>
{{msg}}<br/><br/>
{{description}}
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}- Новое обращение{% endblock %}
{% block content %}
<h2>Вход в систему</h2>
<div style="position:relative">

<form method="post" action="/login/">    
    <input type="text" name="login"/>
	<input type="password" name="password"/>
    <input type="submit" value="Войти"/>
</form>
</div>
{% endblock %}

templates/message_list.html
{% extends "base.html" %}
{% block title %}- Обращение №{{ticket.id}} {% endblock %}
{% block content %}
<div style="position:relative">
<div id="ticket_messages">
    <label>Ответить по email:</label>
    <form method="post" action="/ticket_reply/">
    <textarea name="msg_txt" id="id_reply"></textarea>
    <input type="submit" value="Отправить"/>
    <input type="hidden" value="{{ticket.id}}" name="ticket_id" />
    </form>
    <table style="border-color:black">
    {% for m in msgs %}
    
    <tr>
      <td>{% if m.reply %}&lt;&lt;out{% else %}&gt;&gt;in{% endif %}</td>
      <td>{{m.time|date:"d.m.Y H:i"}}</td>	  
      <td>{{m.text}}</td>	  
    </tr>

    {% endfor %}
    </table>
    
</div>
<div id="ticket_form">
	{% if mail_error %}
	<div class="mail_error">Отправка email не удалась<br/>Ошибка: {{mail_error}}</div>
	{% endif %}	
    <form method="post" action="/edit_ticket/">
    
    <input type="hidden" name="ticket_id" value="{{ticket.id}}"/>
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
	{{form.errors}}
    <div class="field_wrapper">
    <label>Обращение #</label>
    {{ticket.id}} от <a href="/user/{{ticket.user.id}}">{{ticket.user.name}}</a> ( {{ticket.user.phone}} , {{ticket.user.mobile}} ) {{ticket.ctime|date:"d.M H:i"}}
    </div>
    <div class="field_wrapper">


    </div>
        {% if form.instance.is_new %}
    <!--<input type="checkbox" name="accept" value="accept"/><label>Беру на выполнение</label>-->
    {% else %}
            <label>Взял на выполнение: </label> {{form.instance.admin.name}}
            {% if form.instance.is_closed %}
            <label>Закрыто: </label> {{form.instance.closing_time|date:"d.m.Y H:i"}}
            {% endif %}
    {% endif %}

	{% for field in form.visible_fields %}		
		<div class="field_wrapper">	
		{{field.label_tag}}
		{{field}}
		</div>    		
	{% endfor %}
  
    <input type="submit" value="Применить"/>
    </form>
</div>
</div>
{% endblock %}

templates/places.html
{% extends "base.html" %}
{% block title %}- Структура{% endblock %}
{% block head%}

<script type="text/javascript" src="/media/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/media/js/jquery-ui-1.8rc3.custom.min.js"></script>
<script type="text/javascript" src="/media/js/jstree/lib/jquery.cookie.js"></script>
<script type="text/javascript" src="/media/js/jstree/jquery.jstree.js"></script>
<script type="text/javascript" src="/media/js/my_forms.js"></script>
{# load jquery_validation #}
{# include_validation #}
<link type="text/css" href="/media/smoothness/jquery-ui-1.8.2.custom.css" rel="stylesheet" />
<link rel="stylesheet" href="/media/js/jstree/themes/classic/style.css" />

<script type="text/javascript" >

 

 $(document).ready(function(){
	//--------------------------Скрываем формы-------------------------------------
   //$("td.doc_title").children().hide();

   $("#place_form").hide();   
   $("#device_form").hide();
   $("#document_form").hide();
   $("#select_user").hide();
   
	//Place
   $("a.add_place").click(function(event){
   	show_form__(event,"place","место","add",400,function(form_id){
   		$("#id_parent").val("{{root.id}}");
   	});
   });
   $("a.edit_place").click(function(event){
   	show_form_(event,"place","место","edit",400)
   });
   
   //--------------------------Устройство-------------------------------------
   $("a.add_device").click(function(event){
   	show_form__(event,"device","устройство","add",500,function(form_id){
   		$("#id_place").val("{{root.id}}");
   	});
   });   	
   $("a.edit_device").click(function(event){
   	show_form_(event,"device","устройство","edit",500)   	
   });

	//--------------------------Документ-------------------------------------  
   //$("a.add_doc").click(expand_form_);
   $("a.add_doc").click(function(event){
   		$('#document_form input[name=name]').val('');
   		$('#document_form input[name=comment]').val('');
	  	$('#document_form').dialog({modal: true, width: 400, 
   		resizable: false,title: "Добавить документ"});
   		event.preventDefault();  	
	});
	
   $("a.add_ver").click(function(event){
   		
   		id=event.target.id.split('_')[1];
   		$.getJSON('/ajax/document/'+id, function(data) {
	   		for (field in data[0].fields){
	  			$('#document_form input[name='+field+']').val(data[0].fields[field]);	  
		  	}
	  		$('#document_form input[name=doc_id]').val(id);

		  	$('#document_form').dialog({modal: true, width: 400,	  	 
   			resizable: false,title: "Обновить документ"});
   		});
   		event.preventDefault();
   		  	
	});
	//--------------------------Пользователь-------------------------------------
	$("a.add_user").click(function(event){
		$('#select_user').dialog({modal: true, width: 400, 
   		resizable: false,title: "Выбрать пользователя"});
   		event.preventDefault();
	});


	$("#search_user").click(function(event){
		$("a.user").remove();
		var srch_name=$('#user_srch_string').val();
		$.getJSON('/ajax/users',{ name: srch_name }, function(data) {
			for (i in data){
				block='<a href="/user_to_place/'+data[i].id+'/{{root.id}}" class="user" id=\"user_'+data[i].id+'\">'+data[i].name+'</a><br/>';
				$(block).prependTo("#searched_users");
	   		}
	   	});
		event.preventDefault();
	});
	  
   //--------------------------Дерево-------------------------------------
   $("#place_tree").jstree({ core: { initially_open : ["place_0"],animation : 10},themes:{theme: "classic"},
   							"plugins"  : [ "themes", "html_data", "cookies" ] 
   							});   

   var arr=$("#place_tree").jstree("get_path","#place_{{root.id}}",true);
   for (i in arr){   	
	   	$("#place_tree").jstree("open_node","#"+arr[i],false,true);
   }
   
 });

//    $(function()    {        
//        $('#device_form').validate('{% url device_form_validate %}', {type: 'table'});
//    });


</script>
{% endblock %}
{% block content %}

<div id="place_tree" class="place_tree" >
<ul>
{{tree|safe}}
</ul>
</div>

<div class="place_card">
	<h3>
	{% ifnotequal root.level 0 %}
	{{root.level_display}} - 
	{% endifnotequal %}
	{{root.name}}</h3>

	<div class="path">
{% for place in root.path %}
	: <a class="path" href="{{place.get_absolute_url}}">{{place.name}}</a>
{% endfor %}
	</div>


	<a href="" class="add_place">[добавить место]</a>
	<a href="" class="edit_place" id="place_{{root.id}}">[править место]</a>
	<a href="/del_place/{{root.id}}">[удалить место]</a><br/>

<ul>
{% for usr in root.users %}
	<li>{{usr.name}}</li>
{% endfor %}
</ul>
<a href="" class="add_user">[связать с пользователем]</a>
<ul>
{% for dev in devices %}
<li><a href="" class="edit_device" id="dev_{{dev.id}}">{{dev.type_display}} - {{dev.inv_no}}</a>&nbsp;<a class="delete_device" href="/delete_device/{{dev.id}}">[удалить]</a></li>
{% endfor %}
</ul>
	<a href="" class="add_device">[добавить устройство]</a>
	
{% if docs %}	
<ul>	
{% for doc in docs %}
		<li><a href="down">{{doc.name}}</a>	
		<span class="doc_details">
		{{doc.latest_file.ctime|date:"d.m.Y H:i"}} - {{doc.latest_file.user.login}}
		</span>
		<a class="add_ver" href="" id="doc_{{doc.id}}">[правка]</a>		
		</li>
		
{% endfor %}
	</ul>	
{% endif %}
	<br/>
	<a href="" class="add_doc">[добавить файл]</a>
	<br/>	
{% comment %}
	<div class="place_child_container">
{% for town in root.childs %}
		<div class="place_child"><a href="/places/{{town.id}}">{{ town.name }}</a></div>
{% endfor %}
<br clear="all" />	
	</div>
	{% endcomment %}
</div>

			
			<form method="post" id="place_form">			
			<input type="hidden" id="place_id" name="id" value="" />
			<input type="hidden" id="id_parent" name="parent" value="" />
			<table class="form">    
			    {{place_form.errors}}
				{% for field in place_form.visible_fields %}				
					<tr>
					<td>{{field.label_tag}}</td>
					<td>{{field}}</td>
					</tr>
				{% endfor %}
			    
			    <tr>
			    <td colspan="2"><input type="submit" value="Сохранить"/></td>
			    </tr>
			 </table>
			</form>

			<form method="post" id="device_form">
			<table class="form">			    
				{% for field in device_form.visible_fields %}				
					<tr>
					<td>{{field.label_tag}}</td>
					
					<td>{{field}}</td>
					</tr>
				{% endfor %}
				{% for field in device_form.hidden_fields %}
					{{field}}
				{% endfor %}
				
				<input type="hidden" id="device_id" name="id" value="" />							    
			    <tr>
			    <td colspan="2"><input type="submit" value="Сохранить"/></td>
			    </tr>
		    </table>
			</form>
			
			<form method="post" action="/doc_upload/" enctype="multipart/form-data" id="document_form">
				<table class="form">			    
				{% for field in form.visible_fields %}				
					<tr>
					<td>{{field.label_tag}}</td>
					<td>{{field}}</td>
					</tr>
				{% endfor %}
				
				<input type="hidden" name="place_id" value="{{root.id}}" />
				<input type="hidden" name="doc_id" value=""/>
			    <tr>
			    <td colspan="2"><input type="submit" value="Сохранить"/></td>
			    </tr>
			   	</table>
			</form>
			
			<div id="select_user">
			<form>
			<input type="text" id="user_srch_string"/>
			<input type="submit" value="Поиск" id="search_user"/>
			</form>
				<div id="searched_users">
				</div>			
			</div>

{% endblock %}

templates/ticket_list.html
{% extends "base.html" %}
{% block title %}- Просмотр заявок{% endblock %}
{% block content %}

<div class="pagination">
    <span class="step-links">
        {% if tickets.has_previous %}
            <a href="?page={{ tickets.previous_page_number }}"> &lt;&lt; </a>
        {% endif %}

        <span class="current">
            Стр.: {{ tickets.number }} из {{ tickets.paginator.num_pages }}.
        </span>

        {% if tickets.has_next %}
            <a href="?page={{ tickets.next_page_number }}"> &gt;&gt; </a>
        {% endif %}
    </span>
</div>

<table style="border-color:black">
    <tr>
	  <th>#</th>
      <th>Статус</th>
      <th>Получено</th>
      <th>От:</th>
	  <th>Описание</th>

    </tr>

{% for t in tickets.object_list %}

    <tr>
	  <td>{{t.id}}</td>
      <td><a href="{% url edit "ticket" t.id %}">{{t.get_status_display}}</a><br/><span class="priority">{{t.get_priority_display}}</span></td>
      <td class="time">{{t.ctime|date:"d.M H:i"}}<br/><span class="hours">{{t.hours_from_now}} ч. назад</span></td>
      <td><span class="user"><a href="/edit_user/{{t.user.id}}">{{t.user.name}}</a></span></td>
	  <td class="ticket_text">
	  {{t.get_short_text}}
	  <img src="/media/cat_{{t.category}}.png" title="{{t.get_category_display}}" align="right" style="padding-left:5px"/>
	  
	  
	  </td>
       
    </tr>

{% endfor %}

</table>
{% endblock %}